# Persiapan

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
koneksi = sqlite3.connect("amazon_sales.db")

In [ ]:
kursor = koneksi.cursor()

# NO. 1

In [ ]:
#Mengimport data dari excel
ImportDataTabelAmazonSales = pd.read_excel('Amazon Sales - Praktik Mandiri 2 Modul 3.xlsx')

In [ ]:
#Memindahkan data excel ke sql
ImportDataTabelAmazonSales.to_sql('salesamazon', koneksi, if_exists='replace')

1465

In [ ]:
#Isi tabel salesamazon
pd.read_sql_query(""" SELECT * FROM salesamazon LIMIT 1""",koneksi)

,index,product_id,product_name,category,discounted_price,actual_price,discount_percentage,qty,rating,rating_count,order_date,arrival_date,about_product,user_id,user_name,review_id,review_title,review_content
0,0,B0912WJ87V,Reffair AX30 [MAX] Portable Air Purifier for C...,Car & Motorbike,2339.0,4000.0,0.42,6,3.8,1118,2003-02-24 00:00:00,2003-02-26 00:00:00,[NEW LAUNCH - INNOVATIVE DESIGN] EFFICIENT PUR...,"AG6W5HESRSDLBX3NCYOOUGFOWERA,AED4U5CF37HVSYPMD...","Arivazhagan,Ajit,swanand pandit,Venkatesh S.,S...","R3TOOFPX256D59,R1PR50BDQOEIIO,R392FI4QWXWOX5,R...","Liked it,User friendly and effective,Not as pe...","As of now its working fine, but don't expect m..."

In [ ]:
#Kategori Car & Motorbike
pd.read_sql_query(""" SELECT * FROM salesamazon where category = "Car & Motorbike";""",koneksi)

,index,product_id,product_name,category,discounted_price,actual_price,discount_percentage,qty,rating,rating_count,order_date,arrival_date,about_product,user_id,user_name,review_id,review_title,review_content
0,0,B0912WJ87V,Reffair AX30 [MAX] Portable Air Purifier for C...,Car & Motorbike,2339.0,4000.0,0.42,6,3.8,1118,2003-02-24 00:00:00,2003-02-26 00:00:00,[NEW LAUNCH - INNOVATIVE DESIGN] EFFICIENT PUR...,"AG6W5HESRSDLBX3NCYOOUGFOWERA,AED4U5CF37HVSYPMD...","Arivazhagan,Ajit,swanand pandit,Venkatesh S.,S...","R3TOOFPX256D59,R1PR50BDQOEIIO,R392FI4QWXWOX5,R...","Liked it,User friendly and effective,Not as pe...","As of now its working fine, but don't expect m..."

In [ ]:
#Kategori Car & Motorbike
pd.read_sql_query(""" SELECT * FROM salesamazon where category = "Computers & Accessories" limit 5;""",koneksi)

,index,product_id,product_name,category,discounted_price,actual_price,discount_percentage,qty,rating,rating_count,order_date,arrival_date,about_product,user_id,user_name,review_id,review_title,review_content
0,1,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers & Accessories,399.0,1099.0,0.64,4,4.2,24269,2003-05-07 00:00:00,2003-05-17 00:00:00,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...
1,2,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers & Accessories,199.0,349.0,0.43,6,4,43994,2003-07-01 00:00:00,2003-07-03 00:00:00,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...
2,3,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers & Accessories,199.0,1899.0,0.90,4,3.9,7928,2003-08-25 00:00:00,2003-08-26 00:00:00,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a..."
3,4,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers & Accessories,329.0,699.0,0.53,5,4.2,94363,2003-10-10 00:00:00,2003-10-11 00:00:00,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou..."
4,5,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers & Accessories,154.0,399.0,0.61,1,4.2,16905,2003-10-28 00:00:00,2003-11-06 00:00:00,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th..."

In [ ]:
#Sebutkan 5 kategori yang memiliki rata-rata jumlah potongan harga terbesar. Sebutkan juga masing-masing nilai dari kategori tersebut!
pd.read_sql_query(""" SELECT category, AVG(discount_percentage) AS avg_discount
FROM salesamazon
GROUP BY category
ORDER BY avg_discount DESC
LIMIT 5;""",koneksi)

                  category  avg_discount
0         Home Improvement      0.575000
1  Computers & Accessories      0.540243
2   Health & Personal Care      0.530000
3              Electronics      0.508289
4      Musical Instruments      0.460000

# NO. 2

In [ ]:
#Berapa jumlah user yang memberikan review yang memuat kata 'Good Product' pada produk dengan kategori Computers & Accessories dan Office Products ?
pd.read_sql_query(""" SELECT distinct(category), count(review_title) as jumlah_review  FROM salesamazon
WHERE category IN ("Computers & Accessories","Office Products")
AND (review_title LIKE "%Good Product%" OR review_content LIKE "%Good Product%")
GROUP BY category
;""",koneksi)

                  category  jumlah_review
0  Computers & Accessories            287
1          Office Products             14

# NO. 3

In [ ]:
#Tentukan 5 bulan yang memiliki total sales/revenue terendah pada tahun 2004 (dari seluruh kategori produk kecuali Office Products dan Home & Kitchen). Sebutkan juga nilai setiap revenue nya!
pd.read_sql_query(""" SELECT
category,
discounted_price*qty AS total_sales,
strftime('%m', order_date) AS bulan,
strftime('%Y', order_date) AS tahun

from salesamazon

WHERE order_date >= "2004-01-01"
AND order_date < "2005-01-01"
AND category NOT IN ("Office Products","Home & Kitchen")

GROUP BY bulan, category
ORDER BY total_sales ASC, category
LIMIT 5
;""",koneksi)

                  category  total_sales bulan tahun
0              Electronics        279.0    01  2004
1  Computers & Accessories        350.0    06  2004
2              Electronics        398.0    06  2004
3  Computers & Accessories        498.0    09  2004
4         Home Improvement        498.0    10  2004

# NO. 4

In [ ]:
#Sebutkan kategori apa yang rata-rata waktu pengirimannya paling cepat dan lambat (Tanpa kategori Car & Motorbike dan Toys & Games).
pd.read_sql_query("""
SELECT
  category,
  order_date,
  arrival_date,
  ROUND(avg(julianday(DATE(arrival_date)) - julianday(DATE(order_date)))) AS lama_pengiriman
FROM salesamazon
WHERE category NOT IN ('Car & Motorbike', 'Toys & Games')
GROUP BY category
ORDER BY lama_pengiriman ASC
;""",koneksi)

,category,order_date,arrival_date,lama_pengiriman
0,Musical Instruments,2004-11-04 00:00:00,2004-11-05 00:00:00,3.0
1,Computers & Accessories,2003-05-07 00:00:00,2003-05-17 00:00:00,8.0
2,Electronics,2003-11-12 00:00:00,2003-11-20 00:00:00,8.0
3,Home & Kitchen,2004-11-17 00:00:00,2004-11-27 00:00:00,8.0
4,Office Products,2004-11-25 00:00:00,2004-11-26 00:00:00,8.0
5,Home Improvement,2003-10-05 00:00:00,2003-10-20 00:00:00,9.0
6,Health & Personal Care,2004-11-04 00:00:00,2004-11-17 00:00:00,13.0

# NO. 5

In [ ]:
#Hitunglah AOV pada setiap tahunnya, namun data yang digunakan haruslah data dari awal hingga pertengahan bulan (tanggal 01 - 15) untuk setiap bulannya
pd.read_sql_query("""
SELECT
  total_sales,
  total_order,
  avg(total_sales/total_order) AS aov,
  year
FROM
  (SELECT
    discounted_price * qty AS total_sales,
    COUNT(product_id) AS total_order,
    strftime('%Y', order_date) AS year,
    order_date
  FROM salesamazon
  WHERE order_date BETWEEN strftime('%Y-%m-01', order_date) AND strftime('%Y-%m-15', order_date)
  GROUP BY year) subquery

  group by year
;""",koneksi)

   total_sales  total_order        aov  year
0       1596.0          311   5.131833  2003
1        924.0          317   2.914826  2004
2       1794.0          124  14.467742  2005